app/__init__.py
# Code provided by HBO-ICT
from flask import Flask
from app.db import read_db_config, close_db

def create_app():
    app = Flask(__name__)
    app.config['FLASK_ADMIN_FLUID_LAYOUT'] = True
    app.config['SECRET_KEY'] = 'MYVERYLONGSECRET'
    app.config['MYSQL_CONFIG'] = read_db_config('instance/db.config')

    app.teardown_appcontext(close_db)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    # You should probably configure your own blueprint here:
    #from app.MYBLUEPRINT import bp as events_bp
    #app.register_blueprint(MYBLUEPRINT.bp, url_prefix='/MYBLUEPRINT')

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from flask import request, render_template, url_for, redirect, g
from app.auth import login_required
from app.db import select_all, select_one, execute_query
#Add what needs to be imported here. You probably need to rename that blueprint

@bp.route('/')
def index():
    return render_template("index.html")

@bp.route('/buttons')
def buttons():
    return render_template("buttons.html")

@bp.route('/cards')
def cards():
    return render_template("cards.html")

@bp.route('/charts')
def charts():
    return render_template("charts.html")

@bp.route('/forms')
def forms():
    return render_template("forms.html")

@bp.route('/modals')
def modals():
    return render_template("modals.html")

@bp.route('/tables')
def tables():
    return render_template("tables.html")

@bp.route('/connect')
def connect():
    return render_template("connect.php")


app/templates/base.html
<!doctype html>
<html>
  <head>
    <title>Onze Applicatie - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}"/>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/tailwind.css')}}"/>
  </head>

  <body class="main">
    <nav>
      <ul>
        <a href="{{ url_for('main.index') }}"> <img src="../static/img/socialsync.png" class="socialsync-home" alt="Home"></a>
        <a href="{{ url_for('auth.users') }}">Gebruikers</a>
        {% if g.user %}
          <a href="{{ url_for('auth.logout') }}">Uitloggen</a>
          <a href="{{ url_for('auth.edit') }}">{{ g.user['firstname'] }}</a>
        {% else %}
          <a href="{{ url_for('auth.login') }}">Login</a>
          <a href="{{ url_for('auth.register') }}">Registreren</a>
        {% endif %}
      </ul>
    </nav>
    <header>
      {% block header %}{% endblock %}
    </header>
    <div>
      {% block content %}{% endblock %}
    </div>
    <footer id="footer">
      Hier komt een goede footer.
    </footer>
  </body>
</html>